### ISSUE TITLE
not a in issue but a question

### ISSUE THREAD

**Issue by calvarioTeacher31** [RankWeis/uppercut#35]
thanks for your plugin
I understand the requirement ofuse intellij ultimate to cover JS language

have you consider doing this plugin on vscode so we can still use js language?

**Comment by RankWeis** [comment]
Unfortunately I don't use vscode so I would need to learn about its ergonomics and style first, I think this is probably best left to someone with more experience in these matters. Also my projects are usually born from some level of passion and it's hard for me to take on this extra work when I personally will benefit very little, I know that's not the greatest answer but just trying to be honest here. Sorry!
