### ISSUE TITLE
about some keywords

### ISSUE THREAD

**Issue by calvario-31** [RankWeis/uppercut#38]
I would say thanks again for this plugin. Have a couple of questions regarding the keywords and their colors

first question

I want to highlight if there is some kind of rule for the color of the keywords. I have this small example
![Screenshot 2024-11-05 at 1 48 43 PM](https://github.com/user-attachments/assets/e922190c-c8c7-42ee-9208-204069a0ea50)
![Screenshot 2024-11-05 at 1 49 50 PM](https://github.com/user-attachments/assets/537586aa-90fd-4c06-98c6-47b158528617)

for example the keyword `status` on uppercut is not being highlighted even if it is a reserved keyword on karate DSL I would expect to be also orange

But maybe you have some other thoughts about this? that's why im asking if there is some kind of rule your are following

second question
have you considered changing the `give when then` color from dark green to another? now is kinda hard to read and have the same color of the comments (I also have the same issue with official karate plugin that is grey lol)

**Comment by RankWeis** [comment]
> have you considered changing the give when then color from dark green to another? 

Yes, 100% I have, I just have no eye for this kind of thing and this is the default color style from cucumber plugin that I rely heavily on to do a lot of the work. 

And as for status, easily fixed - https://github.com/RankWeis/uppercut/pull/39
I should really find a list of all keywords but I don't think there's a compiled one out there, so I kind of fly by what we use in our team, and we had never used status directly.

**Comment by calvario-31** [comment]
thanks for the status keyword, if I find more i will ping you
for the color yes i think is a hard thing to standarize. 
If you know a way how i can change the colors maybe i can help you to find some color that are easier to see

**Comment by calvario-31** [comment]
Update: I found karate color scheme, seems Given When Then share the same settings as a comment haha that's why they have the same color

**Comment by calvario-31** [comment]
![image](https://github.com/user-attachments/assets/071f42a8-5427-414a-bbc3-8839e406e629)
i believe this color is easier to see, 
i would only add those color to given/when/then and not the comments since is too bright
Sadly I dont know a way to split between comment and given when then settings

![image](https://github.com/user-attachments/assets/cb77e5b4-ce9a-42e5-a84b-5f65b7dc285e)

if you like this is the hex value: 6DA5FF

![image](https://github.com/user-attachments/assets/027b8314-b17a-4349-81b8-f97ba804845c)

**Comment by RankWeis** [comment]
Rather than changing the default color for everyone who may have gotten used to this by now, I went ahead and separated out those two categories and now you can modify to your preference! 

https://github.com/RankWeis/uppercut/pull/40

**Comment by calvario-31** [comment]
thanks!
