### ISSUE TITLE
More missing keywords

### ISSUE THREAD

**Issue by calvario-31** [RankWeis/uppercut#43]
Hello,

Was testing the plugin and seems there are some important keywords missing to be highlighted:
request
assert
read()

Also found these other ones that are not that mandatory but can come handy
headers
cookie
cookies
params
response
eval

Mostly I was testing the official karate github page, there is a table for the keywords
![image](https://github.com/user-attachments/assets/dc332355-c1fa-44c9-bfd3-5b6397cd5a05)

**Comment by RankWeis** [comment]
Thanks, i will get a release out soon!

**Comment by calvario-31** [comment]
Thanks, seems working!
