### ISSUE TITLE
Minor format issues

### ISSUE THREAD

**Issue by calvario-31** [RankWeis/uppercut#47]
Hello, I found these 2 issues when auto-formatting:

![image](https://github.com/user-attachments/assets/6ccf10bc-bb51-4ef8-a8d9-c1663ae9e519)

- Critical (at least for me) there shouldn't be an space between response and id so should be `response.id`
- No too much critical: there shouldn't be space between read and parenthesis symbol. So should be `read('blablaba')`

**Comment by RankWeis** [comment]
It's surprisingly difficult to get this consistent, but what I've done is made it so it won't add the space if it doesn't exist; but, it won't remove the space if it does already exist. That part is a significant challenge that I'm not sure I'm up for at the moment.

**Comment by calvario-31** [comment]
Hello, thanks for the effort
However this seems to make more issues 

For example in this case the whole scenario won't run 
![image](https://github.com/user-attachments/assets/ad39c134-3aa3-466e-80f0-4daa0fdc5ed0)

```
>>> failed features:
no step-definition method match found for: def schema=read('schema.json')
classpath:jsonplaceholder/comments2/Comments.feature:14
<<<
```

I understand can be a pretty hard edge case to deal with. But this version seems to bring those tricky issues

**Comment by RankWeis** [comment]
I'm taking out this feature temporarily, it'll still do some spacing but not all of it. I'll work on getting it right.

**Comment by calvario-31** [comment]
Thanks, suggest to let me test it prior launching to intellij since can be kinda tricky to find edge cases that can break the runs

**Comment by RankWeis** [comment]
I am taking you up on that! I have something that I've tested with all my files and it seems okay, I've used all your examples as well. It's another bigger change and it feels like there's going to be bugs but I can't find them!

[uppercut-1.2.5-base.jar.zip](https://github.com/user-attachments/files/17780467/uppercut-1.2.5-base.jar.zip)

**Comment by calvario-31** [comment]
will test it thanks

**Comment by calvario-31** [comment]
I found a non deal breaker bug

original:
![image](https://github.com/user-attachments/assets/30b00a2b-50a1-47f4-8efd-e3b10c5ac4d2)

2 spaces became white
![image](https://github.com/user-attachments/assets/4457050a-0f8c-44ad-9427-abddbc3b998c)

Maybe not related to that but kinda weird since there are few purple keywords

**Comment by calvario-31** [comment]
So I found a constant issue
There is no autoformat between Given/When/Then/* and the next keyword

![image](https://github.com/user-attachments/assets/e69922d8-c978-405a-9ec3-ce652efa2e92)

**Comment by RankWeis** [comment]
I think we're getting somewhere decent here! Thanks for the input!
[uppercut-1.2.5-base.jar.zip](https://github.com/user-attachments/files/17780910/uppercut-1.2.5-base.jar.zip)

**Comment by calvario-31** [comment]
thanks seems to much better now

only issue i found is after = symbol it does not formats. Believe because for == symbol you dont want to space?
![image](https://github.com/user-attachments/assets/03ac8bac-40e8-4f68-adb6-53f7037725bb)

**Comment by RankWeis** [comment]
[uppercut-1.2.6-base.jar.zip](https://github.com/user-attachments/files/17781115/uppercut-1.2.6-base.jar.zip)

Only change is that fix so I expect this to be a good version to send out. Will probably do it tonight, exciting stuff! Do you mind if I credit you in the changelog? A simple "Thank you to @calvario-31 on GitHub for contributing time and effort into making this plugin better!"

**Comment by calvario-31** [comment]
thanks man tested it at was working fine
seems good to launch

Yeah that would be cool to be added to the changelog
 Next week I will suggest some couple of features that can be implemented

**Comment by RankWeis** [comment]
The formatting has been almost completely overhauled and I have attempted to test it against a ton of feature files. It seems to work well, and it is now released so I am closing this ticket. But if you have any more issues, please feel free to reopen or create a new ticket!
