### ISSUE TITLE
Issue with <> symbols and scenario outline

### ISSUE THREAD

**Issue by calvario-31** [RankWeis/uppercut#65]
Hello,

Im trying to test scenario outline. However the < symbol is making a space and it makes unable to run the scenario
Also the table keeps on grey, I believe should be colored since im using those variables?

![image](https://github.com/user-attachments/assets/667b2783-24bd-4637-a336-ab104d9e937a)

**Comment by RankWeis** [comment]
[uppercut-1.3.2-base.jar.zip](https://github.com/user-attachments/files/17868623/uppercut-1.3.2-base.jar.zip)
If you would like to try it out, this issue and #64 are resolved. 

From a previous conversation you also mentioned wanting to have go-to declarations fulfilled outside of just 'classpath:', that should now be done as well.

Also from that conversation you mentioned wanting formatting for injected json - I unfortunately don't believe there's a good way of doing this at the moment. I am going to continue looking into it but there may be a bug preventing this from happening on the intellij side.
